--Drop database TareaProgramada;
Use TareaProgramada;
DECLARE @i int;
SET @i=0;
WHILE(@i<5)
BEGIN
	Drop table DBErrores;
	Drop table DeduccionXEmpleado;
	Drop table DeduccionXEmpleadoXMes;
	Drop table Departamento;
	Drop table Empleado;
	Drop table Feriados;
	Drop table MarcaAsistencia;
	Drop table MovimientoDeduccion;
	Drop table MovimientoHoras;
	Drop table MovimientoPlanilla;
	Drop table PlanillaMensual;
	Drop table PlanillaMensualXEmpleado;
	Drop table PlanillaSemanal;
	Drop table PlanillaSemanalXEmpleado;
	Drop table Puesto;
	Drop table TipoDeduccion;
	Drop table TipoDocuIdentidad;
	Drop table TipoMovimiento;
	Drop table TipoMovimientoDeduccion;
	Drop table TiposDeJornada;
	Drop table Usuario;
	Drop table PorcentualNoObligatoria;
	Drop table PorcentualSiObligatoria;
	Drop table FijaNoObligatoria;
	Drop table Jornada;
	DROP TABLE Corrida;
	DROP TABLE DetalleCorrida;
	DROP TABLE TipoOperacion;
	DROP TABLE Bitacora;
	DROP TABLE TipoBitacora;
	DROP PROCEDURE AsociarEmpleadoConFijaNoObligatoria;
	DROP PROCEDURE AsociarEmpleadoConMes;
	DROP PROCEDURE AsociarEmpleadoConPorcentualNoObligatoria;
	DROP PROCEDURE CrearMovimientoCreditoDia;
	DROP PROCEDURE CrearMovimientoDebito;
	DROP PROCEDURE DesasociarEmpleadoConDeduccion;
	DROP PROCEDURE EliminarEmpleados;
	DROP PROCEDURE insertarCatalogos;
	DROP PROCEDURE InsertarEmpleados;
	DROP PROCEDURE InsertarJornada;
	DROP PROCEDURE InsertarMes;
	DROP PROCEDURE InsertarMesXEmpleado;
	DROP PROCEDURE InsertarSemana;
	DROP PROCEDURE InsertarSemanaXEmpleado;
	DROP PROCEDURE insertarUsuario;
	DROP PROCEDURE ListarDeduccionesMes;
	DROP PROCEDURE ListarDeduccionesSemana;
	DROP PROCEDURE ListarMes;
	DROP PROCEDURE ListarSalarioSemana;
	DROP PROCEDURE ListarSemana;
	DROP PROCEDURE ListarUsuarios;
	DROP PROCEDURE MarcarAsistencia;
	DROP PROCEDURE ActualizarSalarioEmpleado;
	DROP PROCEDURE InsertarTipoOperacion;
	DROP PROCEDURE InsertarBitacora;
	SET @i=@i+1;
END