USE TareaProgramada;
SELECT * FROM DeduccionXEmpleado;
SELECT * FROM DeduccionXEmpleadoXMes;
SELECT * FROM Departamento;
SELECT * FROM Empleado;
SELECT * FROM Feriados;
SELECT * FROM FijaNoObligatoria;
SELECT * FROM Jornada;
SELECT * FROM MarcaAsistencia;
SELECT * FROM MovimientoDeduccion;
SELECT * FROM MovimientoHoras;
SELECT * FROM MovimientoPlanilla;
SELECT * FROM PlanillaMensual;
SELECT * FROM PlanillaMensualXEmpleado;
SELECT * FROM PlanillaSemanal;
SELECT * FROM PlanillaSemanalXEmpleado;
SELECT * FROM PorcentualNoObligatoria;
SELECT * FROM PorcentualSiObligatoria;
SELECT * FROM Puesto;
SELECT * FROM TipoDeduccion;
SELECT * FROM TipoDocuIdentidad;
SELECT * FROM TipoMovimiento;
SELECT * FROM TipoMovimientoDeduccion;
SELECT * FROM TiposDeJornada;
SELECT * FROM Usuario;
SELECT * FROM Corrida;
SELECT * FROM DetalleCorrida;
SELECT * FROM TipoOperacion;
SELECT * FROM Bitacora;

SELECT * FROM Bitacora B WHERE B.IdTipoBitacora=2;